FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

RUN --mount=type=secret,id=SECRET_KEY \
    export SECRET_KEY=$(cat /run/secrets/SECRET_KEY) && \
    echo "SECRET_KEY is $SECRET_KEY"

ENTRYPOINT ["node"]
CMD ["web.js"]
